import { readFile, readdir, rm, mkdir, writeFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SRC_TTF = join(ROOT, 'public', 'fonts', 'MiSans VF.ttf')
const OUT_WOFF2 = join(ROOT, 'public', 'fonts', 'MiSans VF-subset.woff2')
const TMP_DIR = join(ROOT, 'node_modules', '.subset-cache')
const TEXT_FILE = join(TMP_DIR, 'chars.txt')
const FONTS_CSS = join(ROOT, 'src', 'styles', 'fonts.css')

// ── 1. 收集项目实际用到的字符 ──────────────────────────────────────────
const SCAN_EXTS = ['.md', '.mdx', '.astro', '.svelte', '.ts', '.js']
const SKIP_DIRS = new Set(['node_modules', 'dist', '.astro', 'assets'])

const chars = new Set()

// 基础字符：始终包含
// - ASCII 可见字符 U+20..U+7E（含 7/8/9/q/z/V/Z 等旧 subset 缺失的字符）
for (let cp = 0x20; cp <= 0x7e; cp++) chars.add(cp)
// - 换行 U+0A
chars.add(0x0a)
// - 常见排版字符（remark-smartypants 会生成这些）
;[
  0x2013, // – en dash
  0x2014, // — em dash
  0x2018, // ' left single
  0x2019, // ' right single
  0x201c, // " left double
  0x201d, // " right double
  0x2026, // … ellipsis
  0x00a9, // ©
  0x2122, // ™
  // 中文标点
  0x3000, 0x3001, 0x3002, // 　 、 。
  0x300a, 0x300b, // 《 》
  0x300c, 0x300d, // 「 」
  0x300e, 0x300f, // 『 』
  0x3010, 0x3011, // 【 】
  0xff01, 0xff08, 0xff09, 0xff0c, 0xff1a, 0xff1b, 0xff1f, // ！（） ， ： ； ？
].forEach((cp) => chars.add(cp))

async function scanDir(dir) {
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) await scanDir(join(dir, entry.name))
      continue
    }
    if (!SCAN_EXTS.some((ext) => entry.name.endsWith(ext))) continue
    const content = await readFile(join(dir, entry.name), 'utf8').catch(() => '')
    for (const ch of content) {
      const cp = ch.codePointAt(0)
      if (cp > 0x1f) chars.add(cp) // 跳过控制字符
    }
  }
}

console.log('Scanning source files for used characters...')
await scanDir(join(ROOT, 'src'))

// ── 2. 用 pyftsubset 子集化（保留可变字体 fvar/gvar 轴） ────────────────
const text = [...chars]
  .sort((a, b) => a - b)
  .map((cp) => String.fromCodePoint(cp))
  .join('')

console.log(`Collected ${chars.size} unique codepoints. Subsetting with pyftsubset...`)

await rm(TMP_DIR, { recursive: true, force: true })
await mkdir(TMP_DIR, { recursive: true })
await writeFile(TEXT_FILE, text, 'utf8')

await new Promise((resolve, reject) => {
  const args = [
    SRC_TTF,
    `--text-file=${TEXT_FILE}`,
    `--output-file=${OUT_WOFF2}`,
    '--flavor=woff2',
    '--no-hinting',
    '--desubroutinize',
    // pyftsubset 默认保留 fvar/gvar/HVAR/MVAR/STAT/GDEF/GPOS/GSUB
  ]
  const proc = spawn('pyftsubset', args, { stdio: 'inherit' })
  proc.on('error', reject)
  proc.on('close', (code) =>
    code === 0 ? resolve() : reject(new Error(`pyftsubset exited with code ${code}`)),
  )
})

await rm(TMP_DIR, { recursive: true, force: true })

// 读取文件大小做对比
const outSize = (await readFile(OUT_WOFF2)).length
console.log(
  `Done: MiSans VF-subset.woff2 = ${(outSize / 1024).toFixed(0)} KB (${chars.size} glyphs)`,
)

// ── 3. 计算 unicode-range 并更新 fonts.css ────────────────────────────
function computeUnicodeRange(codepoints) {
  const sorted = [...new Set(codepoints)].sort((a, b) => a - b)
  const ranges = []
  let start = sorted[0]
  let prev = sorted[0]
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === prev + 1) {
      prev = sorted[i]
    } else {
      ranges.push([start, prev])
      start = sorted[i]
      prev = sorted[i]
    }
  }
  ranges.push([start, prev])
  return ranges
    .map(([s, e]) => {
      const hex = (n) => n.toString(16).toUpperCase().padStart(2, '0')
      return s === e ? `U+${hex(s)}` : `U+${hex(s)}-${hex(e)}`
    })
    .join(', ')
}

const unicodeRange = computeUnicodeRange(chars)

const newFontFace = `/* BEGIN:MiSans (auto-generated by scripts/subset-fonts.mjs — do not edit) */
@font-face {
  font-family: 'MiSans';
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("/fonts/MiSans VF-subset.woff2") format('woff2');
  unicode-range: ${unicodeRange};
}
/* END:MiSans */`

let css = await readFile(FONTS_CSS, 'utf8')
const marker = /\/\* BEGIN:MiSans[\s\S]*?\/\* END:MiSans \*\//
if (marker.test(css)) {
  css = css.replace(marker, newFontFace)
} else {
  // 首次运行：替换旧的 MiSans @font-face 块
  const oldBlock = /@font-face\s*\{[^}]*font-family:\s*'MiSans'[^}]*\}/
  css = css.replace(oldBlock, newFontFace)
}
await writeFile(FONTS_CSS, css)

console.log('Updated src/styles/fonts.css with computed unicode-range.')
console.log(`unicode-range: ${unicodeRange.slice(0, 120)}${unicodeRange.length > 120 ? '...' : ''}`)
